# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SorterUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from SortData import SortData


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setMinimumSize(QtCore.QSize(540, 720))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        MainWindow.setFont(font)
        self.file_path = ""
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, -1, 541, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxFileBrowser = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBoxFileBrowser.setObjectName("groupBoxFileBrowser")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBoxFileBrowser)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 511, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutFileBrowser = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutFileBrowser.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayoutFileBrowser.setObjectName("horizontalLayoutFileBrowser")
        self.btnFileBrowser = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnFileBrowser.setFont(font)
        self.btnFileBrowser.setDefault(True)
        self.btnFileBrowser.setFlat(False)
        self.btnFileBrowser.setObjectName("btnFileBrowser")
        self.horizontalLayoutFileBrowser.addWidget(self.btnFileBrowser)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setAcceptRichText(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutFileBrowser.addWidget(self.textEdit)
        self.verticalLayout.addWidget(self.groupBoxFileBrowser)
        self.groupBoxColumnInput = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBoxColumnInput.setEnabled(False)
        self.groupBoxColumnInput.setObjectName("groupBoxColumnInput")
        self.txtColNum = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColNum.setGeometry(QtCore.QRect(210, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColNum.setFont(font)
        self.txtColNum.setObjectName("txtColNum")
        self.lblColNum = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum.setGeometry(QtCore.QRect(30, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum.setFont(font)
        self.lblColNum.setObjectName("lblColNum")
        self.txtColX = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColX.setGeometry(QtCore.QRect(210, 80, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColX.setFont(font)
        self.txtColX.setDocumentTitle("")
        self.txtColX.setObjectName("txtColX")
        self.lblColX = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColX.setGeometry(QtCore.QRect(30, 80, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColX.setFont(font)
        self.lblColX.setObjectName("lblColX")
        self.txtColY = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColY.setGeometry(QtCore.QRect(210, 130, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColY.setFont(font)
        self.txtColY.setObjectName("txtColY")
        self.lblColNum_3 = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum_3.setGeometry(QtCore.QRect(30, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_3.setFont(font)
        self.lblColNum_3.setObjectName("lblColNum_3")
        self.txtColEle = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColEle.setGeometry(QtCore.QRect(210, 180, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColEle.setFont(font)
        self.txtColEle.setObjectName("txtColEle")
        self.lblColNum_4 = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum_4.setGeometry(QtCore.QRect(30, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_4.setFont(font)
        self.lblColNum_4.setObjectName("lblColNum_4")
        self.lblColNum_5 = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum_5.setGeometry(QtCore.QRect(30, 230, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_5.setFont(font)
        self.lblColNum_5.setObjectName("lblColNum_5")
        self.txtColCat = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColCat.setGeometry(QtCore.QRect(210, 230, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColCat.setFont(font)
        self.txtColCat.setObjectName("txtColCat")
        self.lblColNum_6 = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum_6.setGeometry(QtCore.QRect(30, 330, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_6.setFont(font)
        self.lblColNum_6.setObjectName("lblColNum_6")
        self.txtColConcat2 = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColConcat2.setGeometry(QtCore.QRect(210, 330, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColConcat2.setFont(font)
        self.txtColConcat2.setObjectName("txtColConcat2")
        self.lblColNum_7 = QtWidgets.QLabel(self.groupBoxColumnInput)
        self.lblColNum_7.setGeometry(QtCore.QRect(30, 280, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_7.setFont(font)
        self.lblColNum_7.setObjectName("lblColNum_7")
        self.txtColConcat1 = QtWidgets.QTextEdit(self.groupBoxColumnInput)
        self.txtColConcat1.setGeometry(QtCore.QRect(210, 280, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtColConcat1.setFont(font)
        self.txtColConcat1.setObjectName("txtColConcat1")
        self.verticalLayout.addWidget(self.groupBoxColumnInput)
        self.groupBoxBoundInput = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBoxBoundInput.setEnabled(False)
        self.groupBoxBoundInput.setObjectName("groupBoxBoundInput")
        self.txtXBound = QtWidgets.QTextEdit(self.groupBoxBoundInput)
        self.txtXBound.setGeometry(QtCore.QRect(210, 30, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtXBound.setFont(font)
        self.txtXBound.setObjectName("txtXBound")
        self.lblColNum_8 = QtWidgets.QLabel(self.groupBoxBoundInput)
        self.lblColNum_8.setGeometry(QtCore.QRect(30, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_8.setFont(font)
        self.lblColNum_8.setObjectName("lblColNum_8")
        self.txtYBound = QtWidgets.QTextEdit(self.groupBoxBoundInput)
        self.txtYBound.setGeometry(QtCore.QRect(210, 70, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.txtYBound.setFont(font)
        self.txtYBound.setObjectName("txtYBound")
        self.lblColNum_9 = QtWidgets.QLabel(self.groupBoxBoundInput)
        self.lblColNum_9.setGeometry(QtCore.QRect(30, 70, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.lblColNum_9.setFont(font)
        self.lblColNum_9.setObjectName("lblColNum_9")
        self.verticalLayout.addWidget(self.groupBoxBoundInput)
        self.groupBoxSort = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBoxSort.setEnabled(False)
        self.groupBoxSort.setObjectName("groupBoxSort")
        self.btnSort = QtWidgets.QPushButton(self.groupBoxSort)
        self.btnSort.setGeometry(QtCore.QRect(230, 20, 94, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSort.setFont(font)
        self.btnSort.setDefault(True)
        self.btnSort.setObjectName("btnSort")
        self.verticalLayout.addWidget(self.groupBoxSort)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnFileBrowser.clicked.connect(self.openFileBrowser)
        self.btnSort.clicked.connect(self.sort)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxFileBrowser.setTitle(_translate("MainWindow", "File Browser"))
        self.btnFileBrowser.setStatusTip(_translate("MainWindow", "Broser for Excel(.xlsx) Files (Ctrl + F)"))
        self.btnFileBrowser.setText(_translate("MainWindow", "Find File"))
        self.btnFileBrowser.setShortcut(_translate("MainWindow", "Ctrl+f"))
        self.groupBoxColumnInput.setTitle(_translate("MainWindow", "Column Input"))
        self.txtColNum.setStatusTip(_translate("MainWindow", "Column Value of Number"))
        self.txtColNum.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">A</span></p></body></html>"))
        self.lblColNum.setText(_translate("MainWindow", "Number Col:"))
        self.txtColX.setStatusTip(_translate("MainWindow", "Column Value of X"))
        self.txtColX.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">B</span></p></body></html>"))
        self.lblColX.setText(_translate("MainWindow", "X Col:"))
        self.txtColY.setStatusTip(_translate("MainWindow", "Column Value of Y"))
        self.txtColY.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">C</span></p></body></html>"))
        self.lblColNum_3.setText(_translate("MainWindow", "Y Col:"))
        self.txtColEle.setStatusTip(_translate("MainWindow", "Column Value of Elevation"))
        self.txtColEle.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">D</span></p></body></html>"))
        self.lblColNum_4.setText(_translate("MainWindow", "Elevation Col:"))
        self.lblColNum_5.setText(_translate("MainWindow", "Categorey Col:"))
        self.txtColCat.setStatusTip(_translate("MainWindow", "Column Value of Categorey(Type)"))
        self.txtColCat.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">E</span></p></body></html>"))
        self.lblColNum_6.setText(_translate("MainWindow", "Concat 2 Col:"))
        self.txtColConcat2.setStatusTip(_translate("MainWindow", "Column Value of First Concatenation"))
        self.txtColConcat2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">G</span></p></body></html>"))
        self.lblColNum_7.setText(_translate("MainWindow", "Concat 1 Col:"))
        self.txtColConcat1.setStatusTip(_translate("MainWindow", "Column Value of First Concatenation"))
        self.txtColConcat1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">F</span></p></body></html>"))
        self.groupBoxBoundInput.setTitle(_translate("MainWindow", "Bound Input"))
        self.txtXBound.setStatusTip(_translate("MainWindow", "The Bound Value of X"))
        self.txtXBound.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe Print\'; font-size:14pt;\">300000</span></p></body></html>"))
        self.lblColNum_8.setText(_translate("MainWindow", "X Bound:"))
        self.txtYBound.setStatusTip(_translate("MainWindow", "The Bound Value of Y"))
        self.txtYBound.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe Print\',\'Segoe Print\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">700000</span></p></body></html>"))
        self.lblColNum_9.setText(_translate("MainWindow", "Y Bound:"))
        self.groupBoxSort.setTitle(_translate("MainWindow", "Sort"))
        self.btnSort.setStatusTip(_translate("MainWindow", "Start Sorting (Ctrl+Enter)"))
        self.btnSort.setText(_translate("MainWindow", "Sort"))
        self.btnSort.setShortcut(_translate("MainWindow", "Ctrl+Return"))

    def openFileBrowser(self):
        self.file_path = QFileDialog.getOpenFileName(MainWindow, "Find Excel(.xlsx) File", "", "Excel (*.xlsx)")

        if self.file_path:
            self.file_path = self.file_path[0].strip()
            self.textEdit.setText(self.file_path)
            self.groupBoxBoundInput.setEnabled(True)
            self.groupBoxColumnInput.setEnabled(True)
            self.groupBoxSort.setEnabled(True)
        else:
            self.groupBoxBoundInput.setEnabled(False)
            self.groupBoxColumnInput.setEnabled(False)
            self.groupBoxSort.setEnabled(False)


    def sort(self):
        sorter = SortData(\
                self.file_path,\
                self.txtColNum.toPlainText().strip(),\
                self.txtColX.toPlainText().strip(),\
                self.txtColY.toPlainText().strip(),\
                self.txtColEle.toPlainText().strip(),\
                self.txtColCat.toPlainText().strip(),\
                self.txtColConcat1.toPlainText().strip(),\
                self.txtColConcat2.toPlainText().strip(),\
                float(self.txtXBound.toPlainText().strip()),\
                float(self.txtYBound.toPlainText().strip()),\
                )

        sorter.run()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
